version: '3.9'
services:
  customers:
    build:
      context: ./services/customers
    ports:
      - "5001:5001"
  orders:
    build:
      context: ./services/orders
    ports:
      - "5002:5002"
  products:
    build:
      context: ./services/products
    ports:
      - "5003:5003"
  payments:
    build:
      context: ./services/payments
    ports:
      - "5004:5004"
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
